language: node_js

node_js:
  - 6

cache:
  directories:
    - node_modules
    - client/node_modules
services:
  - postgresql

env:
  - NODE_ENV=test

install:
  - yarn install
  - cd client && yarn install

before_script:
  - psql -c 'create database db1-test;' -U Tom

script:
  - npm test
  - cd client && npm test
